receivers:
  otlp:
    protocols:
      http:

exporters:
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  debug:
    verbosity: normal

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/jaeger, debug]
